version: '3'

services:

  postgres:
    image: postgres
    container_name: pgsql-dev
    networks:
      - redarc
    environment:
      POSTGRES_PASSWORD: test1234
    volumes:
      - pgredarc01:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h",  "pgsql-dev", "-U", "postgres"]
      timeout: 10s
      retries: 10

  postgres_fts:
    image: postgres
    container_name: pgsql-fts
    networks:
      - redarc
    environment:
      POSTGRES_PASSWORD: test1234
    volumes:
      - pgftsredarc01:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h",  "pgsql-fts", "-U", "postgres", "-p", "5433"]
      timeout: 10s
      retries: 10

  redarc:
    build:
      context: .
      dockerfile: Dockerfile
    image: redarc
    container_name: redarc
    networks:
      - redarc
    environment:
      # Replace redarc.mysite.org with your hostname
      REDARC_API: http://redarc.mysite.org/api/
      REDARC_SUBMIT: http://redarc.mysite.org/submit/
      SERVER_NAME: redarc.mysite.org
      PGPASSWORD: test1234
      ADMIN_PASSWORD: "qwerty"
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy

  redarc_ingest:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    image: redarc_ingest
    container_name: redarc_ingest
    networks:
      - redarc
    environment:
      INGEST_ENABLED: true
      PG_DATABASE: postgres
      PG_USER: postgres
      PG_PASSWORD: test1234
      PG_HOST: pgsql-dev
      PG_PORT: 5432
      # Reddit credentials
      CLIENT_ID: change me
      CLIENT_SECRET: change me
      PASSWORD: change me
      USER_AGENT: "my user agent"
      REDDIT_USERNAME: "change me"
      INDEX_DELAY: 300
      INGEST_PASSWORD: asdf
    volumes:
      - redarc_ingest_logs:/ingest/logs
    depends_on:
      postgres:
        condition: service_healthy

networks:
  redarc:
    driver: bridge
    name: redarc

volumes:
  pgredarc01:
    driver: local
  pgftsredarc01:
    driver: local
  redarc_ingest_logs:
    driver: local